# Generated by Django 4.2.16 on 2024-12-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('backCover', models.TextField()),
                ('cover', models.BooleanField(default=False)),
            ],
        ),
    ]
